### ISSUE TITLE
[TASK-1] Download the data, try to reproduce the baseline

### ISSUE THREAD

**Issue by konodyuk** [sirius-yandex-nlp-team/laughing_net#1]

**Comment by ilyaphlk** [comment]
Собираюсь:
1) Скачать данные, просмотреть их, найти, есть ли там тест
2) Понять, как парсить
3) Запустить код авторов на этом датасете

**Comment by ilyaphlk** [comment]
Данные уже с test.
Для subtask 1 всего 5 колонок:
id (int), original (str, исходный текст, выделенное слово word помечено как <word/>), edit (str, слово-замена), grades (str из цифр, 5 цифр от 0 до 3 в ряд), meanGrade (float, средняя оценка)
Бейзлайн из таблички воспроизводится, достаточно сконфигурировать окружение как в ридми.

Но я не увидел, где можно в выводе скрипта посмотреть Gain.
